use_frameworks!

platform :ios, '8.0'

target 'HGDatePicker_Example' do
  pod 'HGDatePicker', :path => '../'

  target 'HGDatePicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
